### ISSUE TITLE
publishing on open-vsx.org

### ISSUE THREAD

**Issue by andrascz** [badsyntax/vscode-spotless-gradle#248]
Would you mind [publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) this on open-vsx.org? Gradle Tasks is already [there](https://open-vsx.org/extension/richardwillis/vscode-gradle).

**Comment by badsyntax** [comment]
I attempted to publish but figured out i can't do so because this extension now depends on [`vscjava.vscode-gradle` ](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) and not [`richardwillis.vscode-gradle`](https://open-vsx.org/extension/richardwillis/vscode-gradle).

The Gradle Tasks extension was transferred to Microsoft and in doing so they disabled publishing the Gradle Tasks extension to openvsx. Perhaps you can [open an issue](https://github.com/microsoft/vscode-gradle) asking them to publish to openvsx?

**Comment by andrascz** [comment]
Thanks for the clarification.
